# Generated by Django 2.1.7 on 2019-05-13 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ('polltime',),
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=1000)),
                ('timezone', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polltimes', to='polls.Poll')),
            ],
            options={
                'ordering': ('start', 'end'),
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='polls.Poll'),
        ),
        migrations.AddField(
            model_name='invite',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='polls.Poll'),
        ),
        migrations.AddField(
            model_name='availability',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='polls.Participant'),
        ),
        migrations.AddField(
            model_name='availability',
            name='polltime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PollTime'),
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('poll', 'email')},
        ),
    ]
