# Generated by Django 2.1.7 on 2019-06-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
