# Generated by Django 2.1.7 on 2019-04-04 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ('poll_time',)},
        ),
        migrations.AlterModelOptions(
            name='polltime',
            options={'ordering': ('start', 'end')},
        ),
        migrations.RemoveField(
            model_name='availability',
            name='poll',
        ),
        migrations.AlterField(
            model_name='availability',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='polls.Participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='polls.Poll'),
        ),
        migrations.AlterField(
            model_name='polltime',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polltimes', to='polls.Poll'),
        ),
    ]
