# Generated by Django 2.1.7 on 2019-04-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190404_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='name',
            field=models.CharField(default='GoT Marathon!!!', max_length=100),
            preserve_default=False,
        ),
    ]
