# Generated by Django 2.1.7 on 2019-04-06 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190406_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='poll',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='polls.Poll'),
        ),
    ]
