# Generated by Django 2.1.7 on 2019-04-06 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190406_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='polls.Poll'),
        ),
    ]
