# Generated by Django 2.1.7 on 2019-04-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190406_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ('polltime',)},
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='poll_time',
            new_name='polltime',
        ),
    ]
