# Generated by Django 2.1.7 on 2019-04-08 23:16

from django.db import migrations
from datetime import datetime
import pytz

def add_example_poll(apps, schema_editor):
    Poll = apps.get_model("polls", "Poll")
    User = apps.get_model("polls", "User")
    PollTime = apps.get_model("polls", "PollTime")
    Participant = apps.get_model("polls", "Participant")
    Availability = apps.get_model("polls", "Availability")

    poll = Poll.objects.create(
        name="GoT Marathon!!!",
        author=User.objects.create(
            first_name="Adona",
            last_name="Iosif",
            email="adona.iosif@gmail.com"
        ),
        location="My place",
        notes="Winter is finally here!",
        timezone="America/New York"
    )

    timezone = pytz.timezone("America/New_York")
    time1 = PollTime.objects.create(
        poll=poll,
        start=datetime(2019, 4, 2, 20, 0, tzinfo=timezone),
        end=datetime(2019, 4, 2, 23, 0, tzinfo=timezone)
    )

    time2 = PollTime.objects.create(
        poll=poll,
        start=datetime(2019, 4, 3, 20, 0, tzinfo=timezone),
        end=datetime(2019, 4, 3, 23, 0, tzinfo=timezone)
    )

    p1 = Participant.objects.create(
        poll=poll,
        name="Adona Iosif"
    )

    Availability.objects.create(
        participant=p1,
        polltime=time1,
        availability="M"
    )

    Availability.objects.create(
        participant=p1,
        polltime=time2,
        availability="Y"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190406_2043'),
    ]

    operations = [
        migrations.RunPython(add_example_poll)
    ]
