# Generated by Django 2.1.7 on 2019-05-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20190510_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
